# see defaults at https://jekyllrb.com/docs/configuration/default/
# theme: jekyll-cayman
title: Martin Edström
description: Just another blog

# don't put date in title
permalink: /:title/

# wanna use org instead of markdwon? use a jekyll plugin for it
# markdown: org

# TODO: atom feed plugin https://www.r-bloggers.com/2019/12/creating-an-rss-feed-to-add-your-jekyll-github-pages-blog-to-r-bloggers/

# TODO: search plugin
# TODO: comments plugin

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-org
  - jekyll-remote-theme

remote_theme: pages-themes/midnight@v0.2.0
